---
title: "Hotel_Bookings"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading libraries needed:

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(datasets)
library(funModeling) 
library(Hmisc)
```

## Loading Hotel Bookings dataset:

```{r}
hotels_df = read.csv('hotel_bookings.csv')
```

## Initial data cleanup:

* Changing the reservation status date column to date type:

```{r}
hotels_df$reservation_status_date = as.Date(hotels_df$reservation_status_date, format="%Y-%m-%d")
```

* Changing all character type data columns to factor types:

```{r}
hotels_df = hotels_df %>% mutate_if(is.character, as.factor) %>%
                          glimpse()
```

```{r}
dim(hotels_df)
```

```{r}
head(hotels_df, 6)
```

## Dataset makeup:

```{r}
str(hotels_df)
```

```{r}
describe(hotels_df)
```

## Checking null values:

```{r}
sum(is.na(hotels_df))
```

```{r}
df <- as.data.frame(
  cbind(
    lapply(
      lapply(hotels_df, is.na), sum)
    )
  )

rownames(subset(df, df$V1 != 0))
```

```{r}
hotels_df = hotels_df %>% drop_na(children)
```

```{r}
dim(hotels_df)
```

```{r}
hotels_df
```

## Looking at cancellations for each hotel type:

* Looking at number of booking in the dataset for each hotel type:

```{r}
freq(hotels_df['hotel'], plot = FALSE)
```
```{r}
cancel_df = hotels_df %>% select(hotel, is_canceled) %>%
                group_by(hotel, is_canceled) %>%
                summarise(cancellation_type_count = n()) %>%
                mutate(total_bookings = sum(cancellation_type_count)) %>%
                mutate(percent_cancellation
                     = round((cancellation_type_count/total_bookings)*100, 2)) 
```

```{r}
cancel_df$is_canceled = ifelse(cancel_df$is_canceled == 0,'Not Cancelled','Cancelled')
```

```{r}
cancel_df = cancel_df %>% mutate_if(is.character, as.factor)
```

```{r}
cancel_df
```

```{r}
cancel_df %>% select(hotel, is_canceled, percent_cancellation) %>%
              ggplot(. ,aes(x = hotel, 
                            y = percent_cancellation, 
                            label = percent_cancellation,
                            fill = is_canceled)) + 
              geom_col(stat = "identity", width = 0.7) + 
              geom_text(size = 3.5, position = position_stack(vjust = 0.5), 
                        colour = "white", fontface = "bold") +
              labs(title ="Cancellations per Hotel Type", x = "Type of Hotel",
                       y = "Percentage of total bookings (%)") +
              theme(plot.title = element_text(hjust = 0.5), legend.title = element_blank())
```





