
library(shinydashboard)
library(shiny)

dashboardPage(
  skin = "purple",
  dashboardHeader(title='Hotel Bookings Analysis',
                  titleWidth = 300),
  dashboardSidebar(width = 300,
                   sidebarMenu(
                     menuItem("Introduction",
                              tabName = "intro",
                              icon = icon("h-square")),
                     menuItem("Cancelled/Non-Cancelled Bookings", 
                              tabName = "cancel",
                              icon = icon("concierge-bell")),
                     menuItem("Booking Deposit Type",
                              tabName = "deposit",
                              icon = icon("concierge-bell")),
                     menuItem("Hotel Distribution Type",
                              tabName = "distribution",
                              icon = icon("concierge-bell"),
                              menuSubItem("Total Bookings", 
                                          tabName = "tot_book"),
                              menuSubItem("Average ADR",
                                          tabName = "avg_adr")),
                     menuItem("Repeat/Non-Repeat Guests",
                              tabName = "guest",
                              icon = icon("concierge-bell"),
                              menuSubItem("Total Bookings", 
                                          tabName = "tot_book_guest"),
                              menuSubItem("Weekday/Weekend Nights Bookings",
                                          tabName = "week_day_end")),
                     menuItem("Monthly Cancellations and ADR",
                              tabName = "monthly_adr",
                              icon = icon("concierge-bell")))),
  
  dashboardBody(
    tabItems(
      tabItem(tabName = "intro",
              h2("Introduction to Hotel Booking Cancellation Analysis")),
      tabItem(tabName = "cancel",
              h2("Cancelled and Non Cancelled Bookings ratio by Hotel Types: "),
              fluidRow(box(title = "Plots", plotOutput('freq'),
                           solidHeader = TRUE, status = "primary"),
                       box(title = "Table", 
                           p(strong("Total Number of Cancelled and Non-Cancelled Bookings per Hotel Type: ")),
                           hr(), "**percent_cancellations (%): percentage of total bookings", hr(),
                           tableOutput(outputId ="canceldf"),
                           solidHeader = TRUE, status = "primary")),
              fluidRow(box(title = "Type of Hotel",
                           status = "warning", solidHeader = TRUE, width = 3,
                           radioButtons("hotel_type","Select Hotel Type:",
                                        inline = TRUE, selected = "Both",
                                        c("City Hotel","Resort Hotel","Both"))))),
      tabItem(tabName = "deposit",
              h2("Number of bookings for different deposit types")))))