
library(shinydashboard)
library(shiny)

dashboardPage(
  skin = "purple",
  dashboardHeader(title='Hotel Bookings Analysis',
                  titleWidth = 300),
  dashboardSidebar(width = 300,
                   sidebarMenu(
                     menuItem("Introduction",
                              tabName = "intro",
                              icon = icon("h-square")),
                     menuItem("Cancelled/Non-Cancelled Bookings", 
                              tabName = "cancel",
                              icon = icon("concierge-bell")),
                     menuItem("Booking Deposit Type",
                              tabName = "deposit",
                              icon = icon("concierge-bell")),
                     menuItem("Hotel Distribution Type",
                              tabName = "distribution",
                              icon = icon("concierge-bell"),
                              menuSubItem("Total Bookings", 
                                          tabName = "tot_book"),
                              menuSubItem("Average ADR",
                                          tabName = "avg_adr")),
                     menuItem("Repeat/Non-Repeat Guests",
                              tabName = "guest",
                              icon = icon("concierge-bell"),
                              menuSubItem("Total Bookings", 
                                          tabName = "tot_book_guest"),
                              menuSubItem("Weekday/Weekend Nights Bookings",
                                          tabName = "week_day_end")),
                     menuItem("Monthly Cancellations and ADR",
                              tabName = "monthly_adr",
                              icon = icon("concierge-bell")),
                     menuItem("Takeaways/Conclusion",
                              tabName = "conclu",
                              icon = icon("h-square")))),
  
  dashboardBody(
    tabItems(
      tabItem(tabName = "intro",
              h2("Introduction to Hotel Booking Cancellation Analysis")),
      
      tabItem(tabName = "cancel",
              h2("Cancelled and Non Cancelled Bookings ratio by Hotel Types: "),
              fluidRow(box(title = "Cancelled vs Non-Cancelled Barplot",
                           plotOutput('freq', height = "450px", width = "750px"),
                           solidHeader = TRUE, status = "info"),
                       box(title = "Bookings Table", 
                           p(strong("Total Number of Cancelled and Non-Cancelled Bookings per Hotel Type: ")),
                           hr(), "**percent_cancellations (%): percentage of total bookings", hr(),
                           tableOutput(outputId ="canceldf"),
                           solidHeader = TRUE, status = "info")),
              fluidRow(box(title = "Type of Hotel:",
                           status = "success", solidHeader = TRUE, width = 3,
                           radioButtons("hotel_type","Select Hotel Type:",
                                        inline = TRUE, selected = "City Hotel",
                                        c("City Hotel","Resort Hotel","Both"))))),
      
      tabItem(tabName = "deposit",
              h2("Number of bookings for different deposit types"),
              fluidRow(box(title = "Bookings by Deposit Type Bar Plots",
                           plotOutput('dep', height = "450px", width = "750px"),
                           solidHeader = TRUE, status = "info"),
                       tabBox(title = "Bookings Table",
                              id = "tabset1", height = "450px",
                              tabPanel("City Hotel", 
                                       hr(), tableOutput(outputId ="depositdf1"),
                                       "0 = Not-Cancelled  1 = Cancelled"),
                              tabPanel("Resort Hotel",
                                       hr(), tableOutput(outputId ="depositdf2"),
                                       "0 = Not-Cancelled  1 = Cancelled"))),
              fluidRow(box(title = "Type of Hotel:",
                           status = "success", solidHeader = TRUE, width = 3,
                           radioButtons("hotel_type2","Select Hotel Type:",
                                        selected = "City Hotel", inline = TRUE,
                                        c("City Hotel","Resort Hotel"))),
                       box(title = "Booking Status:",
                           status = "success", solidHeader = TRUE, width = 3,
                           radioButtons("cancel_type","Select Booking Status:",
                                        selected = 1, inline = TRUE,
                                        c("Cancelled" = 1 ,
                                          "Not-Cancelled" = 0))))),
      
      tabItem(tabName = "tot_book",
              h2("Number of bookings for different Hotel Distribution types"),
              fluidRow(box(title = "Bookings by Distribution Type Bar Plots",
                           plotOutput('dist', height = "450px", width = "750px"),
                           solidHeader = TRUE, status = "info"),
                       tabBox(title = "Bookings Table",
                              id = "tabset2", height = "450px",
                              tabPanel("City Hotel", 
                                       hr(), tableOutput(outputId ="distdf1"),
                                       "1 = Cancelled"),
                              tabPanel("Resort Hotel",
                                       hr(), tableOutput(outputId ="distdf2"),
                                       "1 = Cancelled"))),
              fluidRow(box(title = "Type of Hotel:",
                           status = "success", solidHeader = TRUE, width = 3,
                           radioButtons("hotel_type3","Select Hotel Type:",
                                        selected = "City Hotel", inline = TRUE,
                                        c("City Hotel","Resort Hotel", "Both"))))),
      
      
      tabItem(tabName = "avg_adr",
              h2("Average Daily Rate Evaluation for different Hotel Distribution types"),
              fluidRow(box(title = "Average Daily Rates for each distribution type",
                           plotOutput('avg_adr', height = "450px", width = "750px"),
                           solidHeader = TRUE, status = "info"),
                       box(title = "Distribution of Rates for all bookings",
                           plotOutput('adr_dist', height = "450px", width = "750px"),
                           solidHeader = TRUE, status = "info")),
              fluidRow(box(title = "Type of Hotel Distribution:",
                           status = "success", solidHeader = TRUE, width = 4,
                           selectInput("hotel_dist1","Select Distribution Type:",
                                       selected = "TA/TO",
                                       c("TA/TO","GDS","Direct", "Corporate"))),
                       box(title = "Booking Status:",
                           status = "success", solidHeader = TRUE, width = 4,
                           radioButtons("cancel_type1","Select Booking Status:",
                                        selected = 1, inline = TRUE,
                                        c("Cancelled" = 1 ,
                                          "Not-Cancelled" = 0))))),
      
      
      tabItem(tabName = "conclu",
              h2("Takeways/Conclusion")))))